name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Give execute permission to Jest binary
        run: chmod +x node_modules/.bin/jest
        
      - name: Run Tests
        run: npm test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest

      #- name: Configure kubectl
        #run: |
          #echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
          #export KUBECONFIG=kubeconfig
      - name: Create .kube directory
        run: mkdir -p $HOME/.kube
          
      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Verify kubectl configuration
        run: sudo kubectl get nodes

      - name: Verify Kubernetes Cluster Connectivity
        run: sudo kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          kubectl create -f k8s/deployment.yaml
          kubectl create -f k8s/service.yaml
      
  notify:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Deployment Status: ${{ job.status }}'
          body: |
            Hello,

            The deployment pipeline for your Node.js application has completed with status: ${{ job.status }}.

            Regards,
            CI/CD Pipeline
          to: reddygnanesh.rg@gmail.com
          from: noreply@github.com
